Review
TimofeyGoncharov/blog-customizer pull request #2
Opened 2024-05-16 18:36 UTC by TimofeyGoncharov

2024-05-17 01:54 UTC, olgalatkina requested changes
Здравствуйте.

**У вас получилась хорошая работа:**
- Почти полностью реализован функционал.
- Проект соответствует макету на сколько это возможно.
- Обработчик сохранения данных вызывается при отправке формы.
- Код хорошо типизирован.

**Но есть несколько моментов, которые надо поправить:**

- [ ] Не работает основной функционал:
    1. По клику на кнопку СБРОСИТЬ должны сбрасываться стили для статьи до дефолтных.
    2. Сайдбар должен закрываться по клику за пределами сайдбара. Возвращаемся к решению с кастомным хуком. При надо написать **свой** хук и учесть, что обработчик не должен висеть всегда на документе - его нужно вешать в момент открытия и удалять в момент закрытия. Нет необходио отслеживать событие, если сайдбар закрыт. Свой хук пишите в отдельном файл `useClose.ts` в папке `hooks` на одном уровне с папкой `components`. 
- [ ] Попробуйте использовать отдельные стейты для каждого `Select` и `RadioGroup`.
- [ ] Для условного добавления стилей лучше воспользоваться библиотекой `clsx`.
- [ ] Вернуть `gap` для управления расстоянием между элементами формы.
- [ ] Вернуть сайдбару первоначальную ширину.

**Правки можно лучше остаются на ваше усмотрение:**
- [ ] Для одиночных селекторов не стоит использовать библиотеку `clsx`.
- [ ] Лучше вынести компонент `App` в отдельный файл.
- [ ] Можно пофиксить стили, чтобы не было дыры в фоне.
- [ ] По названию должно быть понятно, что хранится в стейте или в переменной, а для обработчиков событий применять глагол `handle `или приставку `on`

Успешного рефакторинга!

2024-05-17 01:54 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={`${styles.container} ${
**Надо исправить:**
Чтобы добавлять стили по условию, достаточно воспользоваться библиотекой `clsx` (уже есть в проекте). Это требование есть в чек-листе: https://ru.paste.pics/89320309e689ee231362c674cd5bd828

Возможно, в этой статье вы найдёте больше информации: https://habr.com/ru/articles/649381/. 

**Замечание относится ко всему проекту.**

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	width: 633px;
**Надо исправить:**
Нужно вернуть контейнеру его ширину. Не стоит изменять внешние размеры контейнера, чтобы избавиться от горизонтальной прокрутки. Тем более, что остальные свойства, завязанные на этот размер вы не поправили.

Проблема возникает и-за фиксированной ширины формы, значит её и будем решать, поменяем у класса `.form` одно свойство: `width: 100%;`
При этом нужно изменить значение свойства `overflow` у класса `.container`. Подробнее тут: https://doka.guide/css/overflow/ 

**Можно лучше:**
Можете попробовать решить интересную задачу - избавиться от дыры в фоне: https://yadi.sk/d/vuaa63kbTNbERQ

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +						<Space />
**Надо исправить:**
Всё же тут нет равнозначного решения прошлому варианту работы. Стоит вернуть свойство `gap` и отказаться от использования компонента `Space`.

2024-05-17 01:54 UTC, olgalatkina commented on src/index.tsx
>  			className={clsx(styles.main)}
**Можно лучше:**
Для одиночных селекторов не стоит использовать библиотеку `clsx`, лучше исправить этот момент здесь и в компоненте `Article`.

2024-05-17 01:54 UTC, olgalatkina commented on src/index.tsx
>  const App = () => {
**Можно лучше:**
Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [openSideBar, setOpenSideBar] = useState(false);
**Можно лучше:** 
Булевы значения принято называть с приставкой `is` , например `isFormOpen`

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const buttonSendForm = (event: SyntheticEvent) => {
**Можно лучше:**
1. В React для типизации события  формы используется тип `FormEvent<HTMLFormElement>`  
2. Нужно использовать в названии функции глагол, описывающий действие, которое выполняет функция, а для обработчиков событий применять глагол `handle` или приставку `on`. Замечание относится ко всем обработчикам.

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [sideBarState, setSideBarState] =
**Нужно исправить:**
Есть другое решение, которое не будет совпадать с прошлым вариантом работы: попробуйте использовать для каждого `Select` и `RadioGroup` свой стейт.

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					<form onSubmit={buttonSendForm} className={styles.form}>
**Отлично:**
Обработчик сохранения данных вызывается при отправке формы - отличное решение.

2024-05-17 01:54 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +			{openSideBar && (
**Надо исправить:**
Условный рендеринг не подойдёт для другого варианта решения, удаляем.

2024-05-17 20:57 UTC, TimofeyGoncharov reviewed
code review

2024-05-18 19:48 UTC, olgalatkina requested changes
Здравствуйте.

**Осталось исправить пару моментов:**
- Использовать другое решение для компонента `ArticleParamsForm`. Подробности в комментариях прошлого ревью.
- Удалить неиспользуемый проп или использовать его.

Все замечания **можно исправить** из этого и прошлого ревью остаются на ваше усмотрение.

Успешного рефакторинга!

2024-05-18 19:48 UTC, olgalatkina commented on src/components/button/Button.tsx
> +		<button className={clsx(styles.button)} type={type} onClick={onClick}>
**Можно лучше:**
Рекомендация была **НЕ** использовать библиотеку `clsx` для одиночных селекторов.
Т.е. раньше было правильнее: `className={styles.button}`.

2024-05-18 19:48 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
>  		<>
**Можно лучше:**
У вас уже есть внешний див, использование `React.Fragment` избыточно, лучше удалить.

2024-05-18 19:48 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [sideBarState, setSideBarState] =
**Нужно исправить:**
Не выполнена рекомендация прошлого ревью. Вам нужно написать другой вариант работы, а не сводить к тому решению, которое уже было. 
Единственное место, где возможно принципиально другое решение -  в компонгенте `ArticleParamsForm`.

2024-05-18 19:48 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	articleState: ArticleStateType;
**Нужно исправить:**
Вы не используете этот проп. Его нужно либо удалить, либо использовать.

2024-05-18 19:48 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +export const ArticleParamsForm = (props: IArticleParamsFormProps) => {
**Можно лучше:** 
Можно использовать деструктуризацию пропсов сразу в параметрах компонента, это распространенная практика

2024-05-18 19:48 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +export const ArrowButton: React.FC<ArrowButtonProps> = (
**Можно лучше:**
Начиная с 17 реакта уже нет необходимости использовать `FC`. Можем использовать обычные функции и если есть - типизировать пропсы:
```
type ArrowButtonProps = {
	onClick: OnClick;
	isOpenSideBar: boolean;
};

export const ArrowButton = ({ onClick, isOpenSideBar }: ArrowButtonProps) => {
    // код компонента
}
```
Это более явный и современный способ типизации и создания функционального компонента в React без использования `FC`.

2024-05-19 10:53 UTC, olgalatkina approved these changes
Здравствуйте.

**Хорошая работа. Проект принимается**🎉

Успехов в дальнейшем обучении!

2024-05-19 17:59 UTC, closed without merging